function [alpha,beta,gama] = DirectKinematics(thetas)

cosBeta = -sin(thetas(2) + thetas(3))*cos(thetas(5)) - cos(thetas(2) + ...
    thetas(3))*cos(thetas(4))*sin(thetas(5));
beta = acos(cosBeta);

if sin(beta) ~= 0
  numeratorAlpha = sin(thetas(5))*(sin(thetas(1))*sin(thetas(4)) + ...
      sin(thetas(2) + thetas(3))*cos(thetas(1))*cos(thetas(4))) - ...
      cos(thetas(2) + thetas(3))*cos(thetas(1))*cos(thetas(5));
  denominatorAlpha =  sin(thetas(5))*(cos(thetas(1))*sin(thetas(4)) - ...
      sin(thetas(2) + thetas(3))*cos(thetas(4))*sin(thetas(1))) + ...
      cos(thetas(2) + thetas(3))*cos(thetas(5))*sin(thetas(1));
  alpha = atan2(numeratorAlpha,denominatorAlpha);
  
  numeratorGama = cos(thetas(2) + thetas(3))*cos(thetas(6))*sin(thetas(4)) -...
      sin(thetas(2) + thetas(3))*sin(thetas(5))*sin(thetas(6)) + ...
      cos(thetas(2) + thetas(3))*cos(thetas(4))*cos(thetas(5))*sin(thetas(6));
  denominatorGama = cos(thetas(2) + thetas(3))*cos(thetas(4))*cos(thetas(5))*...
      sin(thetas(6)) - sin(thetas(2) + thetas(3))*cos(thetas(6))*sin(thetas(5))-...
      cos(thetas(2) + thetas(3))*sin(thetas(4))*sin(thetas(6));
  gama = atan2(numeratorGama,denominatorGama);  
end

 % o que fazer caso contrário
end

